config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'
  resources :posts do
    resources :comments
  end  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
	has_many :comments,dependent: :destroy
	validates_presence_of :title
	has_one_attached :image
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
before_action :set_post

 def create
	comment = @post.comments.create! comments_params
	CommentsMailer.submitted(comment).deliver_later
	CommentsChannel.broadcast(comment)
	redirect_to @post
 end

private
  def set_post
 	@post = Post.find(params[:post_id])
  end
 
  def comments_params
 	params.required(:comment).permit(:body)
  end
end	

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]

  # GET /posts or /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end
  def destroy
  
  end  
  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :body, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.erb
<p><%= comment.body %> -- <%= comment.created_at.to_s(:long) %></p>

app/views/comments/_new.html.erb
<head>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
</head>
<body class="bg-light">
<div class="container">
<%= form_for([@post, Comment.new], remote: true) do |form| %>
<h4>Your Comment:</h4>
<%= form.text_area :body, size: '50x5' %><br>
<%= form.submit class: 'text-light btn btn-primary' %>
<% end %>
</div>
</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
     <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <title>Dilara's Web Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <h5><%= form.label :title %></h5>
    <%= form.text_field :title, class: 'form-control' %>
  </div>
<div class="field">
  <h5>You have to upload an <%= form.label :image %>!</h5>
  <%= form.file_field :image, class: 'form-control' %>
  <br><h5>Current Image:</h5>
   <% if post.image.present? %>
    <%= image_tag(post.image, width: '50%') %><br>
    <% end%>
</div>
  <div class="field">
    <h5><%= form.label :body %></h5>
    <%= form.text_area :body, class: 'form-control' %>
  </div>

  <div class="actions">
    <%= form.submit class: 'btn btn-primary btn-block' %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<head>
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

</head>
<body class="p-5 bg-light">
	<%= link_to 'Back', posts_path, class: 'text-light btn btn-primary' %>
	
<br><br>
	<div class="row">
		<div class="col-md-12">
			<div class="card">
				<div class="card-body">
					<h1 class="card-title"> Editing Post</h1>
					<%= render 'form', post: @post %>

				</div>
			</div>
		</div>
	</div>

 
</body>

app/views/posts/index.html.erb
<!DOCTYPE html>
<html>
<head>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
</head>

<body class='bg-light'>
<br>
  <div class="container">
    <h1 class="d-flex justify-content-between mb-4"> Best Recipes <%= link_to 'New Post', new_post_path, class: 'text-light btn btn-primary' %>
    </h1>
<br>
<p id="notice"><%= notice %></p>

<% @posts.each do |post| %>
  <%= link_to post, class: 'text-decoration-none' do %>
    <div class="card mb-3 p-3">
      <div class="card-body">
      <h5 class="card-title mb-1 text dark"><%= post.title %></h5>
      <p class='text-secondary'><%= post.body %>
      </p>
    </div>
    </div>
  <% end %>
<% end %>
<br>
<br>
</div>
</body>
</html>

app/views/posts/new.html.erb
<head>

	  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
</head>
<br><br>

<body class="bg-light">
<div class="container">
<h1>New Post</h1>
<%= render 'form', post: @post %>
<%= link_to 'Back', posts_path,class: 'text-light btn btn-primary' %>
</div>
</body>

app/views/posts/show.html.erb
<head>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
<style>
	img{
		max-width: 100%;
	}
</style>
</head>
<body>
	<div class="container">


<p>
  <div class="card-body">
  	<div class="card-title mb-1 text-dark">
  		 <h3><%= @post.title %></h3><br>
  	  		 <%= image_tag(@post.image) %>
<p class="text-secondary">
  <%= simple_format(@post.body) %>
</p>
  	</div>
  </div>
</p>

<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_post_path(@post), class: 'text-light btn btn-primary'%> 
<%= link_to 'Destroy', post_path(@post), class: "text-decoration-none text-light btn btn-primary", method: :delete, data: { confirm: 'Are you sure?' } %>
<%= link_to 'Back', posts_path, class: 'text-light btn btn-primary' %>

<br><br>
<h2 class="d-flex justify-content-between mb-4">Comments</h2>


<div id="comments">
<%#Expands to render partial : 'comments/comment', collection: @post.comments %>
<div class="card">
<div class="card-body">
<%= render @post.comments %></div>
</div>
</div>
<div class="card-body">
<%= render 'comments/new', post: @post %></div>
</div>
</div>
<br><br>
</body>